class Selected {
    nsfw = false;
    counter = 1;
    aliveNotifications = 0;
    searching = false;
    shadowTopics = [];
    searchWord = '';
    frequencyMap = new Map();

    constructor() {
        this.shadowTopics = this.topics;
        let values = Math.floor(Number(this.parseParam('topic')));
        void 0 !== values
            ? 'number' == typeof values[1] &&
            values[1] > 0 &&
            values[1] <= this.topics.length &&
            (this.counter = values[1])
            : this.randomize(),
            this.updateDisplay();
        this.topics.push('Denna sida innehåller ' + (this.topics.concat(this.sensitive_topics).length + 1) + ' frågor/samtalsämnen');
    }

    findDuplicates() {
        for(let i = 0; i < this.length; i++){
            this.checkSentenceExists(this.topics[i])
                .then(result => {
                    console.log(result);
                })
                .catch(error => {
                    console.error(error);
                });
        }
    }
    get searchWord() {
        const retval =
            this._searchWord.length > 0
                ? `&question=${encodeURIComponent(this._searchWord)}`
                : '';
        return retval;
    }
    set searchWord(value) {
        this._searchWord = value;
    }
    set counter(value) {
        this.counter += value;
        this.updateDisplay();
    }
    get counter() {
        return this.counter;
    }
    get length() {
        return this.topics.length;
    }
    sensitive_topics = [
        'Är du troende?',
        'Har du några fobier?',
        'Är du ett äckel?',
        'Bästa låten under sexy time?',
        'Skulle doften av en person få dig att vägra sex?',
        'Är religion viktigt?',
        'Vilket är det sexigaste yrket?',
        'Vad är det mest tabu du äger?',
        'Går du på medicin?',
        'Har du någon kink som du inte vågar prata om?',
        'Spelar bröststorlek någon roll?',
        'Beskriv din värsta upplevelse med en partner.',
        'Har du haft sex i ett badkar/en dush?',
        'Har du någonsin haft sex i en säng som inte är din?',
        'Har du haft sex på en toalett?',
        'På en skala mellan 1-10, hur snygg måste en person vara för att du ska ha sex med dem?',
        'Visste du att en mans könsorgan kan regleras i storlek beroende på hur kåt han är?',
        'Vilken är den konstigaste plats du haft sex på?',
        'Hur brukar det kännas för dig att ta intiativ till sex? Tycker du det är lätt eller svårt?',
        'Vilket parti röstar du på?',
        'Vad tycker du bäst om när det gäller "förspel" (t.ex. kramar, kyssar och smekningar)?',
        'Vad kan man göra för att ge dig maximal njutning?',
        'Vad innebär "bra sex" för dig?',
        'Bryr du dig om storleken på en killes, någon roll? Ska den vara stor, medel eller liten?',
        'Vad får dig att känna dig sensuell?',
        'Vad är din syn på sexuella rollspel?',
        'Har du några fetisher?',
        'Tror du på en högre makt?',
        'Vad är det dummaste du gjort mot en vän?',
        'Kan du känna prestationspress när du har sex?',
        'Vad brukar göra att du inte blir sugen på sex?',
        'Vilka kläder tycker du är sexiga?',
        'Har du fortfarande känslor för ett ex?',
        'Vilka underkläder skulle du älska att se mig i?',
        'Hur många har du legat med?',
        'Har du haft sex i en skog?',
        'Tror du att himmel och helvete finns?',
        'Gillar du quickies?',
        'Har du någonsin mist någon nära?',
        'Tycker du att jag brukar märka när du är sugen på sex? Vad kan vi göra för att jag inte ska missa dina signaler?',
        'Vad tycker du om att se varandra i ögonen under sex?',
        'Vad gillar du mest med din egen kropp?',
        'Hur känns det för dig om en av oss får orgasm och inte den andra? Är det olika beroende på om det är du eller jag som kommer?',
        'Vissa personer brukar vilja känna sig nära sin partner innan de har sex och andra personer brukar vilja ha sex för att känna sig nära. Vad stämmer bäst in på dig?',
        'Vilken tid på dygnet tycker du mest om att ha sex?',
        'Hur kan jag bidra till att du känner mer trygghet när vi är intima med varandra?',
        'Finns det någon del av din kropp som du skulle vilja att jag gav mer uppmärksamhet sexuellt? På vilket sätt gillar du att bli berörd där?',
        'Har du varit på en begravning?',
        'Har du en sexfantasi?',
        'Hur känner du gällande att höra om sexuella fantasier som jag har?',
        'Vad är ditt mest livsförändrande ögonblick?',
        'Vad är du nyfiken på att prova sexuellt som vi inte gjort förut?',
        'Upplever du är det är någon skillnad på att "ha sex" och "att älska"? Vad är i så fall skillnaden?',
        'Vad upplever du är de 3 viktigaste sakerna för att sex ska kännas bra för dig?',
        'Vad brukar göra att du känner dig redo för beröring?',
        'Vad gjorde det bästa sexet du haft till det bästa?',
        'Vilka faktorer brukar påverka om du har lätt eller svårt att få orgasm?',
        'Är du dominant eller inte?',
        'När fick du din första kyss?',
        'Hur ofta tycker du om att ha sex?',
        'Vad fick dig att få dåligt självförtroende?',
        'Skulle du kunna bryta mot lagen?',
        'Vad blir du avtänd på?',
        'Har du sexleksaker? Vilka?',
        'Har du någonsin haft en sexuell fantasi om mig?',
        'Den värsta sexupplevelsen?',
        'Vad är det du inte gillar med mig?',
        'Vad tänder du mest på under sex?',
        'Vad tänder du på?',
        'Tror du på ett liv efter detta liv?',
        'Vad hindrar dig från att göra det första steget mot din dröm?',
        'Har du någon favorit sexposition?',
        'Vågar du använda sexleksaker med en partner?',
        'Du är med en ny person, du märker att personen vill ha sex, men du vill inte. Kan du säga nej?',
    ];
    topics = [
        'Visste du att kroppen har 206 ben i skelettet?',
        'Vilken är din favorit-subreddit?',
        'Heter det buntband eller kattstrypare?',
        'Är du en organiserad person?',
        'Kan man ha relationer som inte blir sexuella?',
        'Vad är din definition av barnsligt?',
        'Visste du att en av anledningarna att man kan vara mer trött är för att man avbryter en REM-cykel? Testa byt tid på larmet.',
        'Skulle du klara av att gå med ögonbindel i 24 vakna timmar?',
        'Kan du vad slangen sway, woke, slay queen, simp, fr, pov eller tfw står för?',
        'Vilka dialekter gillar du?',
        'På en skala mellan 1-10, hur tekniskt skulle du anse dig själv vara?',
        'Äger du en kamera?',
        'Do you or do you not feel bonita?',
        'Är det värt att äga en bil trots kostnaderna?',
        'Använder du hellre Postnord eller Schenker?',
        'Vilken är den roligaste tecknade figuren?',
        'Kan du vicka på öronen?',
        'Vilken mobil var din första?',
        'Hur gick det på jobbet idag?',
        'Vad har du för nummer?',
        '<a href="https://www.youtube.com/watch?v=s90ZrJS7BBU" target="_blank">Vines</a> var riktigt najs att ha i sitt liv.',
        'Vilka språk kan du?',
        'Hur vet man att du är glad?',
        'Hur lätt är det att göra dig arg?',
        'Vilket är bäst, pizza, hamburgare eller kebab?',
        'Har du någonsin fått en böter?',
        'Vem gav dig ditt smeknamn?',
        'Är Beck en bra serie?',
        'Skulle du beskriva dig som en ren person? (välstädat hemma, rent)',
        'Kroppen har cirka 600 muskler',
        'Kan du skillnaden på tampong, binda och trosskydd?',
        'Känner du någon tidspress, som om du har för lite tid?',
        'Har du haft något husdjur?',
        'Visste du att en stark blixt innehåller cirka 100 miljoner volt, med ungefär 150\'000 ampere. En normal blixt är 30m volt med 20\'000 ampere. Med formulan<br>kilowatt = (amps * volt)/1000<br>vet man därför att en normal blixt kan driva en genomsnittlig TV i 7.5m timmar.',
        'Vad äter du som tröstmat?',
        'Kan du vicka på näsvingarna?',
        'Hur många mariekex tror du att du kan få plats med samtidigt i din mun utan att tugga dem?',
        'Kan du buktala?',
        'Säger någons färgval på kläder något om dem?',
        'Vad heter den hemska figuren i Mumin som är iskall och fryser allt hon vidrör?',
        'Kan du morra?',
        'Är du en intressant person?',
        'Har du en favoritdrink?',
        'Hur många larm har du?',
        'Vill du ta en fika med mig?',
        'Har du någonsin använt fingerfärg?',
        'Ska vi ta en promenad?',
        'Beskriv det mest negativa med att känna dig.',
        'Bör man diskutera privata saker som kärlek, politik och pengar med kollegor/bekanta?',
        'Vad är det mest löjliga du har övertygat om att någon är sant?',
        'Har du någon gång haft något smeknamn? Vem kom på namnet?',
        'Skulle du kunna tänka dig att raka av allt hår?',
        'Har din familj något “hemligt” släktrecept?',
        'När skrattade du senaste så mycket så du började gråta?',
        'Vad är det konstigaste du någonsin gjort när du var liten?',
        'Har du någonsin gjort en lerfigur?',
        'Berätta en hemlighet om dig själv.',
        'Hur många dagar gammal är du?',
        'När ringde du dina föräldrar senast?',
        'Föredrar du långt eller kort hår?',
        'Har du några säkerhetskameror?',
        'Vilken modell av dammsugare har du?',
        'Skulle du gå med på att hoppa bungee-jump om någon frågade dig "ska vi dra om fem minuter"?',
        'När åkte du pulka senast?',
        'Vad är det fulaste ordet du kan komma på?',
        'Vilken genre av film föredrar du?',
        'Har du testat Linux?',
        'Hur mycket lägger du på spar per månad?',
        'Handlar du på AliExpress/Wish?',
        'När köpte du en dator senast?',
        'Fria tyglar, du har inga ansvar eller begränsningar imorgon, vad skulle du vilja göra?',
        'Vilken är din konstigaste dröm?',
        'Vilken är den vanligaste missbedömningen folk gör om dig?',
        'Vad var det mest pinsamma ögonblicket i ditt liv?',
        'Skulle du hellre kyssa en kobra eller kyssa en skorpion?',
        'Vad är det konstigaste du ätit?',
        'Hur skulle du vilja bli sedd?',
        'Vad är det vackraste ordet för dig?',
        'Vilken serie hade du helst vilja va en del av?',
        'Är du lätt avundsjuk?',
        'Vad är den värsta matkombinationen du kan föreställa dig?',
        'Är du en person som snoozar länge på morgon?',
        'Vilket är ditt lyckligaste tillfälle i ditt liv?',
        'Gillar du naturgodis?',
        'Vad skulle du ta med dig till en öde ö om du bara fick ta med dig en sak?',
        'Nämn 5 saker som du hatar',
        'Tycker du det är attraktivt att vara helrakad på huvudet?',
        'Vad skulle ge för namn till din egna biografi?',
        'Vad är det värsta du gjort mot någon?',
        'Vilket land var det första du reste till?',
        'Vilka typer av människor har du svårt för?',
        'Vad är den mest behagliga accenten att höra ditt språk prata med?',
        'Vad är det bästa rådet din mormor någonsin har gett dig?',
        'Snabbaste eller starkare personen i världen, vad hade du valt?',
        'När du var liten - vad trodde du var det bästa med att vara vuxen då?',
        'Vad är det du ännu gillar, men som du kanske är för gammal för?',
        'Var är ditt drömresmål?',
        'Har du gjort något estetiskt? T.ex. målat en tavla, gjort en lerfigur eller annat?',
        'Blir du lätt andfådd?',
        'Gillar du stark mat?',
        'Föredrar du att synas eller vara dold i sociala sammanhang?',
        'Tar du lätt ledarrollen?',
        'Visste du att en portion juice kan innehålla mer socker än en powerbar?',
        'Är du duktig på att komma på saker att prata om?',
        'Gillar du att vara ute?',
        'Har du lätt för att tugga dig själv i tungan?',
        'Skulle du kalla dig själv för lugn?',
        'Brukar du överförklara dig när du får en fråga som bör ha ett kort svar?',
        'Är det oftast du som kommer på saker att göra?',
        'I Pettsson och Findus fanns små figurer som dels blev fokuset till ett av PC-spelen, vad hette figurerna? De börjar på M.',
        'Vad kan stressa upp dig, trots att det inte är en så storgrej egentligen?',
        'Har du någon förebild?',
        'Har du hittat någon favoritfråga under tiden du använt sidan?',
        'Har du ett lager av förnödenheter för en kvinna hos dig - utifall hon glömt?',
        'Vilka böcker har du läst fler än 1 gång?',
        'Vill du hellre ha en kortare eller längre partner?',
        'Halkar du lätt vintertid?',
        'Vad tror du att folk automatiskt antar om dig när de ser på dig?',
        'Har du några favoritcitat från framgångsrika människor?',
        'Är du en weeb?',
        'Vad tycker du om den nya generationen av människor?',
        'Har du ett bra minne?',
        'Vad är det fulaste du vet i klädesväg?',
        'Brukar du gå på stan i foppatofflor?',
        'Har du någon tro som kan ses som kontroversiell eller stötande?',
        'Vad är det bästa Sverige har att erbjuda?',
        'Hur lätt har du för matematik?',
        'Vad är det mest svenska du vet?',
        '"Kak dela" eller snarare "как дела" betyder "hur mår du" på ryska.',
        'Berätta en rolig sak.',
        'Visste du att sökrutan stödjer RegExp?',
        'Har du sett på The Walking Dead?',
        'Vad är motsatsen till självsäker?',
        'Finns det någonting du sett eller hört om, som du upplever att ingen annan har?',
        'Vilken djurart är den sötaste djurarten?',
        'Är sommaren bästa årstiden?',
        'Vågar du åka båt?',
        'Behåller du grejer från dina ex-partners?',
        'Kan du hålla dig från att spy om du ser någon annan göra det? Låtsas som om de gjorde det precis intill dig.',
        'Gillar du fotboll?',
        'Tycker du om sköldpaddor?',
        'Har du en bucketlist?',
        'Är du en person som gillar drama?',
        'Har du lätt att kommunicera med din partner om problem?',
        'Bråkar du lätt?',
        'Har du ett och samma lösenord på allting?',
        'Gillar du tavlor eller föredrar du att inte ha några?',
        'Hur många foton på familjemedlemmar har du i ditt hem?',
        'Är kakor godare än choklad?',
        'Vilket kaffe är godast?',
        'Gillar du att åka båt?',
        'Har du panikångest?',
        'Maneter ser ut som stora spottloskor.',
        'Har du testat äta bläckfisk?',
        'Vad smakar anka som?',
        'Förstår du hur reglerna är för datumparkering?',
        'Vad heter Mario i efternamn?',
        'Det finns djur som har ögon, som är blinda, som har hud som växer över ögonen.',
        'Gillar du att prata i högtalartelefon?',
        'Hur många kuddar har du?',
        'Har du ett varmt eller kallt täcke?',
        'Tenderar du att lätt bli sjuk?',
        'När du är på gymmet, föredrar du styrke- eller konditionsträning?',
        'Videochattar du någonsin?',
        'Vilken är den bästa såsen?',
        'Går bilen bra?',
        'Säger man Bepsi, Pespi eller Pepsi?',
        'Är det viktigt för dig att se bra ut när du lämnar hemmet?',
        'När borstade du tänderna senast?',
        'Vad tycker du om body-mods? T.ex. implantat eller bygga in teknik i kroppen?',
        'Är ananas på pizza tillåtet?',
        'Är du en reacher eller settler i förhållanden?',
        'Hur allmänbildad är du?',
        'Tävlar du i förhållanden mot andra par?',
        'Har du ett favoritspel som du inte kan släppa?',
        'Är du en självsäker personer eller tvärtom?',
        'Vilken är den bästa frukten?',
        'Har du något guilty-pleasure?',
        'Har du en symaskin?',
        'Vad anser du vara gränsen för att vara en tant eller gubbe?',
        'När bytte du ut alla dina underkläder senast, och hur länge har du ägt dem?',
        'Vilken är din favoritpizza?',
        'Kan du sticka, sy eller tråckla?',
        'Kramar du en kudde när du sover?',
        'Doppar du gärna bröd i resterna av en kokad skinka?',
        'Är skinka överskattat på julbordet?',
        'Visste du att du kan ersätta sköljmedel med ättika?',
        'Firar du en högtid med hjälp av inlagd sill?',
        'Är sandaler med sockar accepterbart?',
        'Är du en introvärt eller extrovärt?',
        'Är du smartare än en hög sand?',
        'Hur tämjer du en häst i Minecraft?',
        'Hur mycket koffein dricker du på en dag?',
        'När gjorde du rent bakom toaletten senast?',
        'Visste du att maximalt daglig rekommenderad dos av koffein är 200mg?',
        'Hur mycket handlar du kläder för per månad?',
        'Vad har du för hörlurar?',
        'Kan du tänka dig leva i en värld utan musik?',
        'Beställer du hem färdig mat mer än du handlar ingredienser?',
        'Hur mycket pengar handlar du för tobak/alkohol per månad?',
        'Vad heter Luigi i efternamn?',
        'Hur länge sitter du vid datorn/tv:n per dag?',
        'Fryser du lätt?',
        'Är du trovärdig?',
        'När insåg du att du var vuxen?',
        'När var du en buse senast?',
        'Sprutgrädde eller göra den själv?',
        'Om du blev tvingad att äta samma sak i en vecka, du får inte äta något annat, vad skulle det vara?',
        'Är grädde bara god med vaniljpulver?',
        'Äter du gröt?',
        'Bästa att äta till frukost?',
        'Har du testat att ha mango i din sallad?',
        'Äger du en sax?',
        'Ger du ofta upp för tidigt?',
        'Bästa dagen i veckan?',
        'Rädd för miljöpåverkan?',
        'Vad är det mest galna en chef bett dig att göra?',
        'Vad gör dig blyg?',
        'Har du någonsin drömt om mig?',
        'Finns det någon bok du hatat - men som alla andra älskat, och vice versa?',
        'Vad har du för uppfattning om mig?',
        'Hur ser ditt drömförhållande ut?',
        'Är det barnsligt att använda slang som "ket" för paket?',
        'Gillar du smällare?',
        'Kan du engelska?',
        'När du duschar, gör du rent mellan tårna då?',
        'Vad är namnet på svenska kungen?',
        'Skulle du våga säga ifrån om någon spelade hög musik på bussen?',
        'Vilka politiska partier finns?',
        'Äger du något vapen?',
        'Köper du dina filmer?',
        'Är du helst hemma tidigt eller spenderar du hellre tid borta?',
        'Gillar du någon specifik växt?',
        'Jobbar du för mycket?',
        'Vilken är den senaste filmen du grät till? Eller skrattade högt till?',
        'Har du mörk humor?',
        'Skrattar du lätt?',
        'Är du alltid för seriös?',
        'Föredrar du långfilmer eller är du mer en sketch-person?',
        'Gillar du lakrits?',
        'Vilket är ditt favoritkonto på Instagram?',
        'Äter du 4 ggr om dagen?',
        'Tar du kort aktivt?',
        'Har du något simborgarmärke?',
        'Läser du böcker?',
        'Har du körkort för den där symaskinen?',
        'Är du lättlurad?',
        'Kan du tänka dig leva i en värld utan choklad?',
        'Vad kan förstöra hela din dag?',
        'Klarar du dig utan din telefon?',
        'Tror du på spöken?',
        'Berätta om den sämsta dejten någonsin.',
        'Vad glömmer du allt för lätt?',
        'Är du en klumpig person?',
        'Kan du skjuta med något vapen?',
        'Samlar du på något?',
        'Vad är mest intressant om dig?',
        'Kan du överleva att inte shoppa en vecka?',
        'Har du någonsin varit med i TV?',
        'iOS eller Android?',
        'Är vitt alla färger eller inga färger?',
        'Dricker du vin?',
        'Är vitt eller rött vin bäst?',
        'Vad tror folk ofta att de har rätt om, men faktiskt inte har det?',
        'Växte du upp med husdjur?',
        'Vilken Final Fantasy är bäst?',
        'Växte du upp på landet, i en by, eller i stan?',
        'Jobbar du helst med händerna, eller är du en person som hellre sitter vid skrivbordet?',
        'Har du något med dig som är awkward?',
        'Hur uttalar man lakrits?',
        'Är du allergisk mot någonting?',
        'Vad är det värsta du vet?',
        'Är du är en morgonperson?',
        'När städade du senast?',
        'Räcker lönen eller lånar du?',
        'Har du något beroende?',
        'Tror du på jultomten?',
        'Har du mat i din kyl just nu?',
        'Vilken julkalender tycker du mest om?',
        'Hur lätt somnar du?',
        'Firar du midsommar?',
        'Tror du på påskharen?',
        'Har kungen något barn?',
        'Sover du mer eller mindre än 8h?',
        'Vad har du för hobbies?',
        'Gillar du pussel mindre än frimärken?',
        'Kan du koda?',
        'Om du kunde leva i en annan tidsepok, vilken skulle du välja och varför?',
        'Vad brukar du ta med dig till lunch?',
        'Har du någon diet du följer?',
        'Hur långt kan du springa innan du kollapsar?',
        'Ser du dig som tränad?',
        'Lever du minimalistiskt?',
        'Hur många pizzor äter du per månad?',
        'Vilken är din största rädsla och hur försöker du hantera den?',
        'Vad är din syn på South park?',
        'Vem är din förebild?',
        'Vad är det bästa att göra på vintern?',
        'Vågar du hoppa höga hopp?',
        'Vem vet mest om dig?',
        'Vem kan du ringa som alltid är på för att hitta på något?',
        'Hur långt är det längsta du någonsin cyklat?',
        'Bästa låten?',
        'Har du någon konstnär du gillar?',
        'Har du fortfarande MP3-spelare?',
        'Vad är det roligaste du och dina föräldrar gjort?',
        'När sa du till dina föräldrar att du älskade dem senast?',
        'Du ska åka på IKEA, vem vet du följer med 5 minuter på sig att lösa allt?',
        'Vilken genre av film är bäst?',
        'Vilken är den bästa sortens kaffe?',
        'Fastnat i TikTok?',
        'Använder du tandtråd?',
        'Bästa parfymen?',
        'Vill du ha barn?',
        'Har du syskon?',
        'Samlar du på konst?',
        'Hur länge är du vaken om dagarna?',
        'Om du tvingas, pizza/hamburgare eller kebab?',
        'När skurade du senast?',
        'Linux, Windows eller MAC?',
        'Hur mycket pengar har du på kontot just nu?',
        'Klarar du av personer som inte använder deo?',
        'Vad är den största skulden du har?',
        'Är du mode-medveten?',
        'Har du någonsin uppfunnit något?',
        'Hur mycket är mycket pengar att spendera på en gång?',
        'När brukar du gå och lägga dig?',
        'Föredrar du att jobba hemifrån?',
        'Vad var ditt första jobb?',
        'Kan du tänka dig att gå på bio ensam?',
        'Är banan på pizza det värsta?',
        'Är du en duktig simmare?',
        'Kan du gå en dag utan deo?',
        'Om du ska vara uppklädd, vad skulle du välja för utstyrsel?',
        'Vill du hellre läsa en bok eller se en film?',
        'Hur ofta duschar du?',
        'Skulle du säga att du inreder bra?',
        'Är du duktig på att komma på samtalsämnen?',
        'Spenderar du mycket pengar på skönhetsprodukter?',
        'Hur många gånger har du bytt frisyr?',
        'Vilken var den första mobiltelefonen du hade?',
        'Gillar du knäckebröd?',
        'Hur många böcker läser du ungefär på ett år?',
        'Vad är den längsta promenaden du tagit?',
        'Har du en känslig mage?',
        'Är du en pratsam person eller är du hellre en som lyssnar?',
        'Bär du hellre slips eller fluga?',
        'Brukar du byta telefon för att du har sönder din?',
        'Vart handlar du?',
        'Är du en person som veckohandlar?',
        'Har du glasögon?',
        'Stör dina grannar dig?',
        'Favorit-leksak när du växte upp?',
        'Har du någonsin vunnit på lotto?',
        'Beskriv dig själv med 3 ord.',
        'Jobbar du bra i grupp?',
        'Känner du dina grannar?',
        'Har du en elskoter?',
        'Har du barn?',
        'Hemmafest eller krogen?',
        'Odla själv eller köpa?',
        'Visste du att nudelpaket inte ska ätas bara som de är? Du kan t.ex. pochera ett ägg i det eller addera tofu till det.',
        'Har du jobbat som volontär?',
        'Brukar du ramla på vintern?',
        'Vilken doft hatar du?',
        'Äter du socker ofta?',
        'Är du en snäll person?',
        'Hur ofta tar du en fika med vänner?',
        'Brukar du springa med saxar?',
        'Har du kraschat bilen någon gång?',
        'Kan du dejta någon oavsett den personens vikt?',
        'När var du på fest senast?',
        'Hur gammal är du?',
        'Kan du se spöken?',
        'När du ser snö, vad tänker du på då?',
        'Visste du att sveriges genomsnitt för längd på kvinnor är 166cm med en vikt på 68kg?',
        'Har du någonsin utövat en vintersport?',
        'Har du lätt för att gå upp i vikt eller kan du äta vad du vill utan konsekvenser?',
        'På en kille, vilken är den bästa kroppsdelen?',
        'Vad har du för hårfärg?',
        'På en tjej, vilken är den äckligaste grejen?',
        'Är lasagne bättre än carbonara?',
        'Vilken är den senaste spelet du grät till? Eller skrattade högt till?',
        'Ur Nintendos lista över karaktärer, vilken är bäst?',
        'Är du tävlingsinriktad?',
        'Vilken låt kan du bara inte släppa?',
        'Är du en dom eller sub?',
        'Kan du gå runt på IKEA i flera timmar?',
        'Bästa såsen?',
        'Vilken tv-serie såg du senast?',
        'Ska det vara kroketter, klyftor, pommes eller rå potatis?',
        'Vad saknar du just nu?',
        'Du är på donken, ska du ha en hamburgare, nuggets eller något annat?',
        'Har du någon du kan prata ut om allting med?',
        'Vilken bilmodell är bäst?',
        'Har du någonsin sett ett spöke?',
        'Har du någonsin krockat med en bil?',
        'Har du någonsin varit orsaken till en olycka?',
        'Rör du på dig tillräckligt?',
        'Man vet aldrig när man kan behöva ett schysst järnrör.',
        'Är du lättövertalad?',
        'Är du en tjej?',
        'Minns du hur det var att ha en MP3-spelare som rymde typ 10 låtar som lika gärna kunde låta idag som en cirkelsåg bara?',
        'Den bästa tecknade figuren är?',
        'Dricker du kaffe svart?',
        'Vilken är din favoritskurk?',
        'Tror du på spöken och andar?',
        'Visste du att sveriges genomsnitt för män är 180cm i längd med en vikt på 84kg?',
        'Har du starkt självförtroende?',
        'Är du en kille?',
        'Hoppa fallskärm, bungee jump eller hajdykning?',
        'Vilket är ditt sämsta köp?',
        'Hur tänker du när du tänker på att bilda familj?',
        'Vill du bli en förälder?',
        'Är Creme fraiche en grej man ska ha i tacos?',
        'Är du, ur ditt perspektiv, vuxen?',
        'Hur tänker du när du tänker på kroppsmodifikationer - t.ex. ta bort en arm bara för att?',
        'Varför ligger du vaken om nätterna?',
        'Har du någonsin eller vill du just nu ändra på din kropp?',
        'Hur mycket kalorier tror du att du äter på en dag?',
        'Är du nöjd över den person du blivit?',
        'Vilken är din favoritlåt just nu?',
        'Tar du hellre trapporna än hissen?',
        '30g parmesanost, 30g pecorino, 4 äggulor, lite salt i en kastrull med 500g färdigkokt pasta och 3dl kvar av pastavattnet, blanda ned 400g pancetta tillsammans med steksmöret ger en fantastiskt god Carbonara.',
        'Varför har du inte gjort det än?',
        'Visste du att genomsnittliga bröststorleken för svenska kvinnor är 34B?',
        'Vilken musik-genre har du fastnat i nu?',
        'Gillar du metal/rock/punk?',
        'Vilket är ditt mål just nu?',
        'Varför har du inte uppnått ditt mål än?',
        'Kan du ge någon av det kön du är attraherad mot en fin komplimang?',
        'Första dejten är här, vad ska du bjuda ut personen på?',
        'Vad har du för drömmar?',
        'Kan du något instrument?',
        'Hur gammal vore du om du var hälften så gammal som du är nu, men två gånger så gammal som du vore då?',
        'Gillar du djur?',
        'Du är hemma ensam, vad hittar du på?',
        "Visste du att en cheeseburgare på McDonald's har ungefär 300 kcal.",
        'Du ska bilda ett företag, vad är din slogan?',
        'Vad håller dig vaken om nätterna?',
        'Har du någonsin fått professionell hjälp för mentala/psykiska problem du haft/har?',
        'Skulle du köpa en katt utan att berätta för din partner?',
        'Om du fick en gratis resa, vart hade du åkt då?',
        'Visste du att associera något med en annan grej kan göra det lättare att minnas något? Att tugga tuggummi medan du lär dig något kan skapa en association mellan de två.',
        'Vilken är den godaste drinken du smakat?',
        'En person du känner skriker åt dig, hur reagerar du?',
        'Vart äter du dig helst in i koma?',
        'Hur mäter du om en person är vuxen?',
        'I vilken stad hade du helst bott i?',
        'Kan du lösa talet?<br>2x-5=15',
        'Vad saknar appar som Tinder och Badoo?',
        'Är en killes längd viktig?',
        'Känner du att det är viktigt att rätta folk som säger fel?',
        'Är grammatik viktigt?',
        'Vilket är det bästa sällskapsspelet?',
        'Skicka en snap till 3 personer, be varje om att få "Kan du beskriva mig med ett ord?".',
        'Vad är den billigaste godaste maträtten?',
        'När lämnade du blodprov senast?',
        'Är du lättroad?',
        'Det mest avtändande en kille kan säga?',
        'Visste du att ha inlärningstillfällen på 30 minuter styck med 5 minuter rast mellan vardera kan öka din förmåga att ta in ny information?',
        'Har du stenkoll på din ekonomi?',
        'Har du bott i samma stad hela ditt liv?',
        'Är du uppvuxen i stan eller på landet?',
        'Vilken är den dummaste investeringen du gjort?',
        'Visste du att fett jämfört med kolhydrater (4) och protein (4) har 9 kcal per gram.',
        'Äger du i dagsläget ett företag?',
        'Vad är det pinsammaste du gjort?',
        'Beskriv med antal föremål av en specifik sort som du väger istället för antal kg.',
        'Visste du att snö är vitt?',
        'Reddit eller Imgur?',
        'Filmer som gjordes förr var bättre?',
        'Hur gammal var du när du lärde dig att simma?',
        'När tog du en promenad senast?',
        'Visste du att det längsta mellanrummet mellan födseln mellan trillingar där en av de 3 föddes 18 dagar ifrån de andra?',
        'Vilket land besökte du senast?',
        'Visste du att du kan få i dig tillräckligt med vitaminer, mineraler, protein, kolhydrater och fett utan att behöva äta kött?',
        'Om du starta ett företag, vad skulle du sälja?',
        'Vad är det bästa/största du uppnått?',
        'Vilket är ditt drömjobb?',
        'Är du tidspessimist eller optimist?',
        'Försöker du lära dig något aktivt?',
        'Äldsta du äger?',
        'Vad var bäst med din uppväxt?',
        'Är smällare och raketer kul?',
        'Är du en sån person som normalt skjuter upp grejer?',
        'Be den du pratar med att komma på något?',
        'Du har haft huvudvärk i 3 dagar, du känner dig överhuvudtaget seg sedan längre tid, vad gör du åt det?',
        'Vad ansåg du var coolt när du var 10-12 år gammal?',
        'När är du född?',
        'Visste du att damm i hemmet normalt är kvalster, bakterier, hår, död hud, spindelnät och ludd?',
        'Att göra en budget där du staplar upp alla utgifter och prioriterar din inkomst är bästa sättet för att börja spara.',
        'Pocahontas, som återspeglas av bland annat Disney var 18 år gammal och föddes 1595.',
        'Alla Ahlgrens bilar har samma smak.',
        'Det är omöjligt att kittla dig själv, det är en överraskning och du får en panik-respons, vilket du inte får av att kittla dig själv.',
        'Det finns inget i matväg som är blått.',
        'En 60 minuters promenad i rask takt kan bränna så mycket som 270 kalorier (varierar såklart), men om du anstränger dig kan du säkert äta en Japp på mindre än 20 sekunder, som har nästan dubbla mängden kalorier (441).',
        'Gillar du kroppskontakt?',
        'När du umgås med polare, vad gör du helst då?',
        'Visste du att ett kilo kroppsfett motsvarar cirka 7700 kcal?',
        'Visste du att en man från Kina trädde 101 nålar med en tråd, med hjälp av sin mun?',
        'Vem saknar du just nu?',
        'Vad har varit en nära döden upplevelse för dig?',
        'Ursäkta mig? Den där andra filuren får komma på något annat att prata om.',
        'Om du var tvungen att välja ett fysiskt krävande jobb istället för ett kontorsjobb, vilket skulle du valt?',
        'Du kan inte andas och svälja samtidigt. Du ser också ganska rolig ut när du försöker.',
        'Har du någonsin tvingat någon att göra någonting, vad?',
        'Vad hade din första bil för bilmärke?',
        'Annas pepparkakor är bästa varianten av köp-pepparkakor.',
        'Du har hemmafest, när ska alla sticka?',
        'Är du en rolig person?',
        'Hur många bilar har du ägt?',
        'Vad är det tyngsta du lyft med händerna?',
        'Om du satt fastbunden i en källare, du får inte sluta titta på en sak på tv:n framför dig, det är 100 timmar tills du friges, vad skulle du välja för klipp (längst 20 minuter) att titta på?',
        'Är du en ärlig person?',
        'Vilken är din favorit disney-film?',
        'Är du duktig på ekonomi?',
        'Visste du att din syn på dig själv är din egen? Många tror och tycker mer om dig än du själv gör.',
        'Visste du att världsrekordet för att spinna en rockring på sin rumpa ståendes är 453 minuter (7h 33m)',
        'Läsk är viktigt?',
        'Tatueringar är skitsnyggt?',
        'Loppisar är bara för fattiga?',
        'Kan du fixa enkla fel på din bil, t.ex. en säkring eller lampa?',
        'Du ska bli överraskad, på ett bra sätt, hur?',
        'Vad är det sämsta du gjort i trafiken?',
        'Skönheten och odjuret var en fransk saga som kom till i början av 1700-talet. Odjurets förbannelse varade i en längd av 10 år och han skildrades ofta som en människa likt ett vildsvin eller stor get med stora betar.',
        'Vad är det svåraste du vet?',
        'Personer har 100% odds att dö under sin livstid.',
        'Finns det ämnen du anser är tabu?',
        'Väder',
        'Did you see that ludicrous display last night<a href="https://www.youtube.com/watch?v=6yN2H3--1aw" target="_blank">?</a>',
        'Har du någonsin haft en partner som avlidit under ert förhållande?',
        'Har du varit med om ett trauma någon gång?',
        'Du får en oväntad faktura på 2000kr, har du råd den 15:e en månad att betala den?',
        'Sämsta valet du gjort i år?',
        'Är laptop bättre än en desktop?',
        'Äger du en dator?',
        'Visste du att en person som faktiskt gillar dig hittar ursäkter och tillfällen att kommunicera med dig utan att du behöver initiera kontakt?',
        'När blev du ordentligt jävla lurad senast?',
        'Godaste energidrycken?',
        'Om du ligger på soffan och ska titta på en sport, vilken sport tittar du helst på?',
        'Hur gammal var du när du tog körkortet?',
        'Dreamworks eller Disney?',
        'Vad gick du för utbildning på gymnasiet?',
        'Har du någonsin blivit utnyttjad av någon på något sätt?',
        'Äger du något pinsamt?',
        'Ska andra rätta sig efter dig?',
        'Om du blev arbetslös just nu, hur länge skulle du klara dig utan ekonomiskt stöd av A-kassa?',
        'Vad är den högsta examen du tagit från för typ av skola?',
        'Du får ett ord för att beskriva dig själv - vad är ordet?',
        'Kommer du hit ofta?',
        'Vilken film skulle du kunna rekommendera till vem som helst?',
        'Tar du itu med grejer?',
        'Bor du på landet eller i stan?',
        'Vilken högtid är viktigast för dig?',
        'Iggar du folk?',
        'Har du en eftergymnasial utbildning, isåfall, i vad?',
        'Vad är den bästa hårfärgen på en partner?',
        'Har du något orimligt skönhetsideal?',
        'Varför är du singel just nu?',
        'Vad är det svåraste med ett förhållande?',
        'Husvagn, skjul, bil, lägenhet, hus, husbil, garage, släpvagn, vad sover du helst i av dem?',
        'Vad med dig kan få en annan person att tänka "wtf"?',
        'Visste du att utseendet på vad du äter spelar mycket större roll än vad det faktiskt smakar?',
        'Står eller sitter du när du torkar dig i rumpan?',
        'När gjorde du senast något fysiskt krävande?',
        'Vad är den bästa överraskningen du kommit hem till?',
        'Vad är den största/värsta kritiken du fått?',
        'Har du någon som du kan be om vad som helst av?',
        'Ni är oense, ni kan inte bestämma er, hur gör ni upp?',
        'Kan du laga fin mat?',
        'Du får en miljon, investerar eller spenderar du?',
        'Har du någonsin bakat lussekatter? Berätta om din upplevelse.',
        'Vad är viktigast när du köper en ny telefon?',
        'Har du någonsin läst en kvällskurs, kurs eller övat in något som inte har med ditt jobb att göra?',
        'Vad är din favoritsyssla när du kommer hem efter jobbet?',
        'Föredrar du att få signaler eller direkta besked?',
        'Vad är du mest tacksam över?',
        'Hur gammal vore du om din syster var 6 år gammal när du var 9 och hennes ålder delat i 2 är 39?',
        'Vad är det största du åstadkommit?',
        'Har du haft en nära-döden-upplevelse?',
        'Vilken var din värsta upplevelse?',
        'Vad vill du jobba med?',
        'Vet du vem Tim Burton är?',
        'Sackosäck eller soffa?',
        'Bryta benet eller armen?',
        'Är du höjdrädd eller "träffa marken från att ha fallit"-rädd?',
        'Har du någonsin varit utomlands?',
        'Bästa turistattraktionen du varit på?',
        'Badar helst ute eller i bassäng?',
        'Hur ofta badar du?',
        'Gillar du bastu?',
        'Hur mycket pengar har du lagt på alla dina kläder?',
        'Hade du klarat av att vara blind i minst 24h?',
        'Har du någonsin varit med en omfattande olycka?',
        'Har du blivit bedragen någon gång?',
        'Har du några bestående men från en olycka?',
        'På en skala mellan 1-10, hur snygg är du?',
        'Hur många par skor har du?',
        'Bästa alkoholen (drink eller rent)?',
        'På en skala mellan 1-10, hur bra minne har du?',
        'Gillar du att prata i telefon medan du är ute och går?',
        'Kan du märka om en person är bra eller dålig?',
        'Vilken kvalité letar du först efter hos en person?',
        'Hur ofta har du varit på gymmet i år?',
        'Vilket spel har du spelat längst?',
        'Längsta promenaden du tagit?',
        'Går du hellre med någon eller ensam?',
        'Lyssnar du hellre på musik eller har det tyst runt dig?',
        'Har du något problem som får dig att t.ex. inte vilja ha på dig vissa plagg, äta viss mat eller dricka viss dryck?',
        'Värsta kvalitén med dig?',
        'Vad vill du jobba på men inte gör det?',
        'Värsta sättet du förlorat en vän på?',
        'Har du ur ditt perspektiv många vänner?',
        'Har du fler kollegor än vänner?',
        'Hur skaffar du helst vänner?',
        'Äger du ett djur?',
        'Ser du dig själv som lat eller aktiv?',
        'Vilken är din favoritaktivitet på gymmet?',
        'Springer du helst på gymmet, hemma eller utomhus?',
        'Någon har precis åkt in på akuten, vad gör du?',
        'Har du en god relation till din närmsta familj (syskon, föräldrar)?',
        'Har du någonsin sminkat dig?',
        'Konstigaste sättet du blivit ihop med en partner?',
        'Hur lång är du?',
        'Vilken är din favoritfärg?',
        'Vad har du för ögonfärg?',
        'Kan du gå in i en butik utan att handla?',
        'Beskriv din perfekta lördag kväll.',
        'Hur irriterande är du?',
        'Är du kreativt lagd?',
        'Hur länge har du jobbat på det jobb du jobbar på nu?',
        'Trivs du?',
        'Hur fick du det jobbet?',
        'Varför är du kvar?',
        'Vad betyder vänskap för dig?',
        'Det är pandemi, klockan är 13:29 på en tisdag, du är ledig, vad gör du?',
        'Det är lördag, klockan är 16:49, du har inte gjort några planer, vad ska du hitta på?',
        'Kan du vara vän med ett ex?',
        'Har du någonsin odlat grönsaker?',
        'Vad blir du helst av med? Dina armar eller ben?',
        'Vad är det knäppaste du gjort påverkad?',
        'Visste du att om du stänger dina ögon är det svårt att se?',
        'Anser du att det är objektifierande att en kvinna har stor urringning på sig och sen blir arg på att en viss man tittar ditåt? Mannen har alltså bara tittat.',
        'Vad har du för blodtyp?',
        'Bästa filmen?',
        'Längtar du till jobbet?',
        'Kan man lita på dig?',
        'Vilken längd hade den kortaste personen du varit med? Allt före gymnasiet räknas inte.',
        'Vad väger mest, ett kilo fjädrar eller ett kilo tegelstenar?',
        'Minns du verkligen hur det var att stå ut med kvalitén av en DVD-film?',
        'Du är 18 år gammal, din lillasyster är 12. Du blir 12 år äldre, hur gammal är din syster efter 6 av de åren?',
        'När du handlar, handlar du efter specifika varor eller efter pris?',
        'Vilken är den äckligaste osten?',
        'Du ska bli bonde, emot din vilja såklart, men vad hade du velat ha för djur om du fick välja vilka?',
        'Vad hatar du mest?',
        'Du är ute och åker, du ska köra 30 mil, vad vill du ha i bilen?',
        'Gör du hellre rätt första gången, till risk att det tar 3x längre tid eller gör du det hellre snabbt och hoppas på det bästa?',
        'Du fick 50 000 SEK, vad går pengarna åt till?',
        'Tittar du fortfarande på Kalle Anka på julafton?',
        'Bor du hellre i lägenhet, hus eller på en gård?',
        'Sonic eller Mario?',
        'Bästa stället att bo på?',
        'Vad värdesätter du mest i en vänskapsrelation?',
        'Vilket är ditt favoritminne?',
        'Vilka tre musikalbum har haft störst inverkan på ditt liv?',
        'Turas om att säga positiva karaktärsdrag hos din dejt. Nämn fem saker var.',
        'Om allt var lagligt och socialt accepterat under en timme, vad hade du då passat på att göra?',
        'Säg tre ”vi”-meningar var. Till exempel: ”Vi båda är i det här rummet och känner…”',
        'Av alla dina familjemedlemmar, vems död skulle vara mest jobbig? Varför?',
        'Vad skulle vara viktigt för din dejt att veta om dig, om ni skulle bli nära vänner?',
        'Vilken dag i ditt liv hade du velat leva om?',
        'Vilket är det värsta jobb du har haft?',
        'Vilken film fick dig senast att börja gråta?',
        'Vilket var ditt favoritspel/lek som barn?',
        'Har du någonting du inte kan leva utan?',
        'Vilka fem ingredienser måste finnas med i tacos?',
        'Du får köpa vilket djur du vill, oroa dig inte om kostnaderna kring det, vilket djur köper du?',
        'Om du var tvungen att välja mellan drama, komedi eller action att titta på resten av livet, vilken skulle du välja?',
        'Har du läst en bok nyligen?',
        "Om du hade ett lån på 30'000 SEK, du kan avbetala det maximalt 1200 per månad, hade du tagit ett extrajobb på helger eller lediga dagar för att kunna avbetala det 6000 SEK i månaden istället?",
        'Katt eller hund?',
        'Ta fyra minuter och berätta din livshistoria så detaljerat som möjligt.',
        'Donerar du pengar till välgörenhet?',
        'Har du blåa ögon till situationer och beslut?',
        'Kan du överväga att ta en påse och plocka upp skräp när du tar en promenad?',
        'Vad är det läskigaste du varit med om?',
        'Investerar du i dig själv? Psykisk hjälp, kläder, god mat och dryck som du känner att du vill ha?',
        'Visste du att du kan reglera din egen andning?',
        'Har du någonsin stulit någonting?',
        'Är du en sosse?',
        'Vad i livet är du mest tacksam för?',
        'Är du snål eller bjuder du när man är ute?',
        'Äger du en bil?',
        'Om du fick leva till att du var 90, och fick ha en 30-årings hjärna eller kropp de sista 60 åren, vad hade du då valt?',
        'Spelar du spel?',
        'Hur länge sover hästar? - Tills de vaknar.',
        'Skicka en fråga till 5 personer, be dem "Berätta om 3 styrkor jag har.". Prata nu med din bästa vän om dessa stämmer och vad ni känner om svaren.',
        'Skulle du beskriva dig själv som en extro- eller introvert?',
        'Vid vilken ålder lärde du dig simma?',
        'Äger du en pyjamas?',
        'Har du någonsin sett ett vilt djur (inte på zoo)?',
        'Har du någonsin jagat förr?',
        'Ska killar ha smink?',
        'Favoritämne under uppväxten i grundskolan/gymnasiet/eftergymnasialt?',
        'Har du varit i skogen och plockat bär?',
        'Favoritklädesplagg?',
        'Kan du simma?',
        'Har du lätt för att vara apatisk?',
        'Vilket är det värsta skämtet du hört?',
        'Ideala första dejten?',
        'Har du någonsin ägt ett GameBoy?',
        'Vad är det mest galna du gjort?',
        'Bästa spelet du spelat är?',
        'Du är ute och går, ser ett barn ensamt, gråter, vad gör du?',
        'Regn eller solsken?',
        'Det är årsdag, du och partnern ska hitta på något, vem bestämmer och vad vill du göra?',
        'Du är en reacher eller settler?',
        'Gillar du svamp?',
        'Har du någonsin plockat svamp?',
        'När hade du kul senast?',
        'Vilken är den godaste chokladen?',
        'Är nötter gott eller överhypeat?',
        'Har du en diagnos?',
        'Är smink viktigt?',
        'Vad är det nördigaste du vet?',
        'Bästa boken du läst?',
        'Spelar du någon sport?',
        'Är du emotionell?',
        'Vågar du säga ifrån?',
        'Ser du dig som en romantiker eller som en relativt neutral person?',
        'Är bio fortfarande kul?',
        'Är du en skeptisk person?',
        'Får du hellre brev eller mejl?',
        'Android eller iOS och varför?',
        'Visste du att alla kvinnor inte bryr sig om kroppsideal?',
        'Är miljön viktig för dig?',
        'Cola zero, Pespi Max, Pespi eller Cola?',
        'Kan du skilja på en åsna och en älg?',
        'Bästa filmen för som passar när som helst?',
        'Vad är det dyraste du har (småting (inte bil/boende))?',
        'Vilket ord stavas fel i alla ordböckerna? - Ordet fel.',
        'Vid vilken ålder lärde du dig cykla?',
        'Vad hette den första skola du gick på?',
        'Har du någonsin avsiktligen fått två personer att inte gilla varann?',
        'Vilken nivå av levnadsstandard skulle du klassa dig i<br><br>a) Hög<br>b) Mellan<br>c) Låg<br><br>Argumentera',
        'Rosor är röda, violer är blå, fattar inte du att det är på två meters avstånd du ska stå?',
        'Varför är du?',
        'Har du haft en KK?',
        'Gillar du ditt jobb?',
        'Vad sträcktittade du på senast?',
        'Är färgat porslin till toan och handfattat på toa lite weird? Typ en blå toa.',
        'Vad kan du som få kan?',
        'Kan du göra slut med någon på grund av hur lite man hjälper till i hemmet?',
        'Skulle du hellre bo i en herrgård eller en lyxig penthouse lägenhet?',
        'Kollar du priset på vad du handlar i matbutiken?',
        'Vad gjorde du i helgen?',
        'Lär du dig fortfarande nya grejer?',
        'Vad lägger du onödigt mycket pengar på?',
        'Vart ser du dig själv om fem år?',
        'Avgör priset kvalitén?',
        'Rött eller vitt vin?',
        'Är det någon skillnad på billiga kläder och dyra kläder?',
        'Är du introvert eller extrovert?',
        'Vad tycker du är viktigt i ett förhållande?',
        'Var tillbringar du mest tid förutom hemma och på jobbet/skolan?',
        'Om du får välja vem som helst i hela världen, vem hade du helst bjudit över på middag?',
        'Äter du ute ofta?',
        'Vad är det värsta du hade kunnat tänka dig att göra på en dejt?',
        'Cykel, gå eller moped, vilken är bättre?',
        'Visste du att många män känner att de får för lite komplimanger?',
        'Vad vill du att andra ska märka om dig?',
        'Är flirtande otrohet?',
        'Nämn tre saker som du tycker att vi verkar ha gemensamt?',
        'Vad tycker du om personer som du pratar med om ett ämne och svarar på din fråga eller ämne, men inte frågar något tillbaka?',
        'Dealbreaker i en relation?',
        'Värsta en kollega gjort mot dig?',
        'Vad får dig att skratta?',
        'Har du någonsin kört över ett djur?',
        'Har du hellre in-ear lurar eller over-ear lurar?',
        'Sämsta dejtupplevelsen?',
        'Sämsta superkraften?',
        'Parfym som luktar bäst?',
        'Hur mycket pengar investerar du i dig själv månadsvis?',
        'Äger du ett par hörlurar?',
        'Favoritsadjektiv att kalla en jobbig person?',
        'Utan att säga namnet på djuret, försök på så udda sätt som möjligt beskriva en anka.',
        'Bästa bilmärket och varför?',
        'Tyngsta du äger?',
        'Vad skulle du bli ihågkommen för?',
        'Vad är det första du letar efter i en person?',
        'Hur gammal var du när du förstod att du inte var rik trots att du hade en hundring i fickan?',
        'Vad vill du få ut av livet?',
        'Skulle du kunna bli tillsammans med en kollega?',
        'Vågar du åka flyg?',
        'Brukar du skotta utanför lägenheten när det snöat?',
        'Kastat sten på fåglar?',
        'Äger du ett ur?',
        'Är julen en grej du firar?',
        'Är tåg bästa färdmedlet för att åka långt inomlands?',
        'Om du fick en grej som du fick ändra med dig själv, vad skulle det vara?',
        'En sak du ångrar?',
        'Vilken är den viktigaste appen på din telefon?',
        'Vad gjorde att du hade det största grälet du någonsin haft och vem vann?',
        'Om du stod på ICA, du ser en gammal gubbe som inte kan betala, det saknas tio kronor, hade du hjälpt honom?',
        'Kassler är det äckligaste',
        'Vad är det viktigaste på julbordet?',
        'Vaccin, för eller emot?',
        'Hur många kan du öppna upp dig till?',
        'På en skala mellan 1-10, hur social är du?',
        'Sämsta livsrådet?',
        'Är du starkt beroende av att köpa grejer?',
        'Är det irriterande när du är den enda som kommer på saker att prata om?',
        'Äckligaste godisen',
        'Det jobbigaste du behövt göra?',
        'Har du stora skulder?',
        'Hur inleder du helst ett samtalsämne med en person du inte känner sedan tidigare?',
        'Pratar du med folk du inte känner på fester?',
        'Har du svårt att somna?',
        'Är du en person som övertänker eller glider igenom livet?',
        'Vad är prio ett efter lönen kommit in?',
        'Vad är din största mentala block?',
        'Är du deprimerad?',
        'Hur ofta borstar du tänderna?',
        'Godaste bäret?',
        'Går du på fördomar, en person har varit med om x eller har diagnosen y, spelar det roll?',
        'En person du inte känner sätter sig ner vid ert bord på krogen, personen känner din vän men inte dig, hur reagerar du?<br><br>a) Tyst och pratar bara om andra pratar<br>b) Initierar och försöker lära känna den andra<br>c) Beskriv med egna ord',
        'Vad skulle du vilja vara känd för?',
        'Behöver du söka hjälp?',
        'Vad är du mest stolt över?',
        'Vilken gubbe ser man aldrig på sommaren? - Snögubben.',
        'Har du en god förståelse för hur aktier eller fonder fungerar?',
        'Har du ett sparkapital?',
        'Blond, brunett, rödhårig eller annat, vad väljer du?',
        'Har du körkort?',
        'Är skägg bra?',
        'Kan du fler alfabet än det svenska?',
        'Kroppshår, ja eller nej?',
        'Spelar vikt någon roll på din partner?',
        'Vilken vodka smakar bäst?',
        'Har du testat Whiskey?',
        'Äter du hälsosamt?',
        'Har du muskler?',
        'Har du styrketränat förr?',
        'Har du ett favoritbröd?',
        'Källsorterar du?',
        'Har du ett intresse du skulle kunna lägga tiotusentals pengar på?',
        'Hur ofta städar du bakom toaletten?',
        'När skrubbade du badkaret senast?',
        'Jobbar du mer hemifrån än på plats?',
        'Vilken klädstil har du?',
        'Är vad du har på dig till gymmet en viktig detalj?',
        'Jeans eller mjukisbyxor?',
        'Har du ett komplex?',
        'Jobbar du trots att du är sjuk?',
        'Vilken är den bästa matbiten på julbordet?',
        'Dricker du öl?',
        'Vilken är den bästa konsollen? (pc master race)',
        'Har du någonsin gjort dina föräldrar riktigt besviken?',
        'Har du varit otrogen?',
        'Vad är det dummaste du gjort?',
        'Ramlat med cykel någon gång?',
        'Har du någonsin vågat hoppa från högsta hopptornet vid sjön?',
        'Har du någonsin tagit cykeln och cyklat ut i sjön?',
        'Gillar du att bli skrämd?',
        'Är du bortskämd?',
        'Ser du hellre på animerat eller inte?',
        '30 grader i värmen eller -30 i kylan?',
        'Längsta tiden du spenderat i någon form av butik?',
        'Visste du att snö smälter vid 0.1 +grader?',
        'Sämsta kvalitén hos en person är?',
        'Vad är det mest attraktiva med din partner?',
        'Hur stora är dina fasta utgifter månadsvis?',
        'Har du någonsin brutit mot lagen? Vad gjorde du?',
        'Vad är det värsta en människa kan göra?',
        'Vilken grundskola gick du på?',
        'En splitter ny bil, ett nybyggt hus enligt dina önskemål eller en familj, vilken väljer du?',
        'Är det viktigt att gilla samma saker i en relation?',
        'Vad var det äckligaste du stoppat i din mun?',
        'Är du en s.k. "social justice warrior"?',
        'Vad är skillnaden mellan en anka?',
        'Du ser ett problem i världen, föredrar du att klaga om det tills du inte längre kan ta andetag eller försöker du rätta det?',
        'När grät du senast och varför?',
        'Vad ville du bli när du var liten?',
        'Vad gav du bort senast till någon?',
        'Du har inget internet och du kommer inte få det förrän imorgon, vad gör du resten av dagen?',
        'Är storlek viktigt för dig?',
        'Vad köpte du sist för möbel?',
        'Är du nöjd med ditt liv just nu?',
        'Vad får dig att le?',
        'Vad väger du?',
        'Mortal Kombat/Killer Instinct/Tekken eller Soul Calibur?',
        'Vad samlar du på?',
        'Vem gjorde slut i er förra relation, varför?',
        'Slutför meningen: Om jag hade en _ skulle jag vara lycklig.',
        'Favoritbilmärke?',
        'Har du många vänner?',
        'Vilken musikgenre lyssnar du helst på?',
        'Vad ska man uppnå med livet?',
        'När anser du att man räknas som vuxen?',
        '<a href="https://www.youtube.com/watch?v=nQ2nL3yKGRc" target="_blank">YouTube</a> är en bra plats för massor med jävla skit, har du ett favoritklipp?',
        'När bör man skaffa barn (ålder)?',
        'Visste du att skräckfilmer är till för att skrämma dig?',
        'Vad köpte du senast?',
        'Mörkläggande gardiner är gåvan från ovan?',
        'Vad är de 4 saker du senast fotade?',
        'Är utseende allt?',
        'Hur mäter du lycka?',
        'Finns det nånstans du vill resa men inte kan pågrund av Covid-19?',
        'Vad är det man har framför sig men ändå inte kan se? - Framtiden.',
        'Är man framgångsrik om man tjänar mycket pengar?',
        'Vore du hellre ensam med mycket pengar eller tvärtom?',
        'Äter du kött?',
        'Beskriv din crush',
        'Hur mår du? Egentligen.',
        'Rumpa eller bröst, vad föredrar du?',
        'Vaknar du tidigt eller sent?',
        'Har du piercingar?',
        'Det blev strömavbrott, en säkring är trasig, vad gör du?',
        'Om du fick bli bra på någonting, vad som helst, vad skulle du vilja vara bra på? Din jävla sopa..',
        'Vet din far att du ej har oskulden kvar?',
        'Har du någonsin haft en partner som varit otrogen?',
        'Oroar du dig över att bli spionerad på av typ TikTok, din telefon i allmänhet eller något annat?',
        'När söp du ner dig själv redigt jävla ordentligt senast?',
        'Rakat eller inte? Skägg alltså.',
        'Vilket är ditt favoritklipp på Youtube?',
        'Beskriv den optimala partnerrelationen',
        'Är det okej att säga saker som "han är stadig" istället för att säga att "han är tjock"?',
        'Vad finns alltid i ditt kylskåp?',
        'Du ska lära dig ett nytt språk, vilket?',
        'Hur kan du förbättra dig själv?',
        'Är pengar det viktigaste?',
        'Vad kan du bara göra i hemlighet?',
        'Hur ofta dammsuger du?',
        'Skurar du någonsin?',
        'Visste du att om du spolar toaletten utan att ha något form av skydd ovanpå toaletten (stängt locket exempelvis) hamnar massvis med bakterier utanför och runt om toaletten?',
        'Sanning eller konka?',
        'Har du någonsin åkt polisbil? Varför?',
        'Varför ska du komma på något? Säg åt den där jäveln i andra änden att komma på något.',
        'Varför skrattar inte du oftare?',
        'Vem känner dig bäst?',
        'Har du tv i sovrummet?',
        'Vad är definitionen av en semester?',
        'Har du någon tatuering?',
        'Vilka skolor har du gått på?',
        'Om du dog idag, säg om 5 minuter för att göra det lätt, vad hade du velat lämna efter?',
        'Vad vill du hinna göra innan du dör?',
        'Hur ofta är det lämpligt att duscha?',
        'Är det du eller din partner i er relation som stökar mest?',
        'Kan du öppna upp dig för din familj?',
        'Om du är uttråkad och du är med någon, tar du ansvar att lösa situationen?',
        'Har du någonsin (även oavsiktligt) dödat ett djur?',
        'Vad är det finaste du äger?',
        'Favorittårta?',
        'Föredrar du en lugn och samlad person eller en med agressiva tendenser?',
        'Bäst pålägg på mackan?',
        'Är du duktig på historia?',
        'Ljusa eller mörka möbler?',
        'Det är helg, du har pengar över, vad är det du vill hitta på?',
        'Du får välja en grej på en person som du ska börja dejta helt fritt, vad väljer du att den personen ska ha?',
        'Vem följer du frenetiskt på YouTube?',
        'Roadtrip nu, direkt, du har 10 grejer som får följa, du har 30 sekunder på dig. Vad ska med?',
        'Men sitt ner och håll käften istället för att prata för en gångs skull...',
        'Om någon behöver hjälp, erbjuder du dig innan du blir frågad?',
        'Är vinter bättre än sommar?',
        'Pysslar du gärna i en trädgård?',
        'Har du skjutit pilbåge?',
        'Hur ofta byter du sängkläder?',
        'Vilket spel kan du spela flera timmar i utan att ens tänka på att du gjort det?',
        'Skulle du snömula ett barn?',
        'Får du lätt abstinens?',
        'Får du lätt blåmärken?',
        'Hur ofta simmar du i sjön på somrar?',
        'När var du på IKEA senast?',
        'Anser du dig själv som optimist eller pessimist?',
        'Kör du skoter regelbundet?',
        'Kan du gå in i en affär och ut utan att köpa något - och ändå känna dig som en kriminell?',
        'Är du spelberoende av kasino-tjänster eller lotteri?',
        'Lägger du dig lätt i vad andra tycker?',
        'Känner du att det är viktigt att dela åsikter?',
        'Om du får din åsikt nedskjuten, försvarar du den?',
        'Vad är det tyngsta fordon du kört?',
        'Hur många gånger har du flyttat?',
        'Vem lärde du känna senast?',
        'Hur många skolor har du gått på?',
        'Har du någonsin misslyckats med en utbildning?',
        'Vad tror du fick in dig i yrket du jobbar i nu?',
        'Vad har din äldre släkt lärt dig som du känner har varit en viktig läxa?',
        'När fick du din första puss?',
        'Prioriterar du dig själv före andra?',
        'Gör du en matsedel över veckan eller kör du bara vad du känner för?',
        'Hur stor säng har du?',
        'Föredrar du drama över reality?',
        'Om du fick vara osynlig en hel dag, vad skulle du göra? Berätta i ordning från att du vaknade.',
        'Du blir erbjuden en befordran, men du får ingen högre lön. Du får fler ansvarsområden, tar du jobbet ändå?',
        'Din syster har problem och behöver att du åker och hjälper henne, hon är 80 mil bort, gör du det?',
        'Skulle du ta ledigt för att hjälpa någon - en dag exempelvis?',
        'Din bil är trasig, lagar du den själv eller ber du någon annan om hjälp?',
        'Vad tar du helst? En trisslott eller en 20-lapp?',
        'Vilken var den första spelkonsolen du spelade på?',
        'Har du ett spelintresse?',
        'Har du någonsin spenderat stora pengar på lotteri och förlorat dem?',
        'Har du något starkt beroende?',
        'När blev du som senast väldigt skrämd? Av vad?',
        'Är du lättskrämd annars?',
        'Halsa eller smutta?',
        'Handlar du när du har tråkigt?',
        'Vodka eller cider?',
        'När gick du på bio senast? Vad såg du?',
        'Du ska gå på semester imorgon, du har tagit ledigt 2 veckor. Alla dina planer blir inställda på grund av en omständighet och du måste nu hitta på något annat, vad gör du istället?',
        'Fiskar du?',
        'Roligaste fordonet att köra?',
        'Osexigaste kroppsdelen?',
        'Tvättar du fötterna när du duschar?',
        'Vad är okej köp att skuldsätta sig för?',
        'Vilket är ditt favoritminne från din barndom?',
        'Lyssnar du på poddar eller ljudböcker?',
        'Vad gillar du mest med ditt nuvarande jobb eller studier?',
        'Har du några resplaner på gång?',
        'Gillar du idrott?',
        'Vilken var den senaste konserten eller liveframträdandet du var på?',
        'Har du några semestertraditioner eller favorittyper av resor?',
        'Vilket är det mest intressanta stället du någonsin varit på?',
        'Pacemaker är en svensk uppfinning.',
        'Har du någon gång gjort något volontärarbete eller samhällstjänst?',
        'Vilken var den senaste boken du läste?',
        'Påverkades du starkt av Covid-19?',
        'Spelar du något tv-spel?',
        'Vilken är den svåraste utmaningen du någonsin mött?',
        'Har du haft någon större effekt av elpriserna?',
        'Vad är dina tankar om det nuvarande politiska klimatet?',
        'Har du några livsmål eller ambitioner?',
        'Vilken är den största skuld du haft?',
        'Är du nöjd över hur valet gått hittills?',
        'Är storlek viktigt?',
        'Är att duscha bättre eller sämre än att bada?',
        'Du får tio miljarder kronor, du är ekonomiskt oberoende för resten av ditt liv såvida du inte byter livsstandard. Hur kommer dina närmaste år se ut?',
        'En nära kompis till dig har hamnat hos kronofogden, hjälper du dem?',
        'En familjemedlem har lånat din bil och kört sönder den, kopplingen bara sa yeet. Kräver du din familjemedlem på att fixa den?',
        'Du har lagt ett löfte, är detta omöjligt att bryta eller är löften för dig något som kan ändras?',
        'Har du någonsin kört en vit månad?',
        'Kan du gå in på en hemsida utan att köpa något?',
        'Har du tagit droger?',
        'Vilket barndomsintresse hade du som du övergett?',
        'James Bond eller Mission Impossible?',
        'Skulle du hellre berätta för din partner om dina problem eller ruva på dem själv?',
        'Om du är oense med någon om en sak, argumenterar du om det eller nöjer du dig med att ni har olika åsikter?',
        'Vad är din favoritsak där du bor?',
        'Du får ett jobberbjudande, jobbet ligger 30 mil bort, du har familj och din nyblivna partner här, tar du jobbet utan att prata med familjen?',
        'Är kärlek prioriterat över din finansiella situation?',
        'Har du några husdjur eller favoritdjur?',
        'Skulle du klassa dig själv som en romantiker?',
        'Är dåligt självförtroende en deal-breaker för dig?',
        'Vad är den mest romantiska gärning du gjort?',
        'Vad är en direkt deal-breaker för dig?',
        'Är parfym viktigt?',
        'Vilket är det bästa råd du någonsin har fått och hur har det påverkat dig?',
        'Har du någonsin varit med en vuxen person som gillat axe?',
        'När anser du att man blir oskuld igen?',
        'Har du campat, eller gillar någon typ av natur- eller utomhusaktiviteter?',
        'Har du någonsin haft en särskilt minnesvärd dröm?',
        'Är antalet sexpartner viktigt för dig?',
        'Är utseende viktigt?',
        'Dyraste du köpt till någon?',
        'Har du någonsin haft en sugar daddy eller sugar mama?',
        'Har du hoppat isvak?',
        'Är du en blyg person?',
        'Har du gjort din läxa?',
        'Kom du ihåg det där du skulle göra imorgon?',
        'Blir du enkelt känslosam?',
        'Har du snapchat?',
        'Bästa minnet från en fylla?',
        'När slog du någon senast och varför?',
        'Är det kallt ute?',
        'Du matchar med någon på Tinder/Badoo/annat, tar du initiativ eller väntar du?',
        'Blir du lätt kall?',
        'Är mysa/gulla ihop på soffan bättre än sex?',
        'Anser du att du är otrevlig om du säger nej?',
        'Vad gör du för arbete eller studier?',
        'Hur gillar du att varva ner efter en lång dag?',
        'Vad jobbar du med just nu?',
        'Har du någonsin varit i <din hemstad här>?',
        'Vilken typ av musik gillar du?',
        'Följer du några idrottslag?',
        'Har du någonsin varit på semester utomlands?',
        'Vilken är din favorittyp av kök?',
        'Är du en morgon- eller nattmänniska?',
        'Gillar du att spendera tid utomhus?',
        'Är du en hundmänniska eller en kattmänniska?',
        'Har du någonsin provat någon extremsport?',
        'Har du någonsin varit på en konsert eller musikfestival?',
        'Är du en spänningssökare eller föredrar du en lugnare livsstil?',
        'Vilka är dina favoritcitat eller ordspråk?',
        'Har du några syskon?',
        'Visste du att Volvo uppfann trepunktsbältet som används i nästan alla bilar idag?',
        'Har du någonsin gjort något volontärarbete?',
        'Vilken typ av mat lagar du helst?',
        'Vilken är den mest intressanta platsen du någonsin besökt?',
        'Har du några husdjur?',
        'Gillar du att resa?',
        'Vilken skulle vara din perfekta dag?',
        'Vilka är dina favorittyper av aktiviteter?',
        'Zip-arkiv uppfanns av en svensk person (Gideon Sundbäck)',
        'Vad är din favoritsak med din hemstad?',
        'Vilken är den bästa semestern du någonsin tagit?',
        'Vad är det viktigaste i ditt liv?',
        'Föredrar du att bo i staden eller på landet?',
        'Har du några talanger eller färdigheter?',
        'Har du några specifika resmål på din bucket list?',
        'Är du en samlare av något?',
        'Vad skulle vara din perfekta helgresa?',
        'Vad skulle vara din drömsemester?',
        'Har du någon typ av favoritväder?',
        'Vilken är din favoritsäsong?',
        'Gillar du stranden eller bergen mer?',
        'Är du en äventyrssökare eller en lugn person?',
        'Vilket är ditt favoritsätt att hålla sig aktiv?',
        'Har du någon favoritform av träning?',
        'Är du ett fan av någon specifik sport?',
        'Har du några historiska favoritfigurer?',
        'Har du någon favoritartist eller musiker?',
        'Är du med i någon ideell förening?',
        'Har du några favoritkaraktärer?',
        'Har du några favoritförfattare?',
        'Vad för sorts person blir du attraherad till?',
        'Vad är det mest äventyrliga du någonsin gjort?',
        'Oroar du dig eller är du nyfiken om AI?',
        'Har du några intressanta hobbyer eller talanger?',
        'Kan du mycket om historiska personer eller händelser?',
        'Har du någonsin lärt dig eller provat något helt nytt?',
        'Finns det någon artist eller musiker som du följer religiöst?',
        'Har du några karaktärer eller böcker?',
        'Vilken är den vackraste plats du någonsin sett?',
        'Har du några fobier eller rädslor?',
        'Har du någon komedi, komiker eller komediprogram som du gillar?',
        'Vad är det roligaste du har haft?',
        'Gillar du teknik eller prylar?',
        'Vilket gymnasie gick du på?',
        'Vad är det mest intressanta du har lärt dig nyligen?',
        'Har du några åsikter om utbildningens nuvarande läge?',
        'Vilken är den mest meningsfulla upplevelsen du någonsin har haft?',
        'Har du några favorithistoriska händelser?',
        'Vad är det roligaste du har haft på semestern?',
        'Vad är det mest intressanta du någonsin sett?',
        'Läser du mycket?',
        'Har du någonsin haft ett särskilt minnesvärt möte med ett djur?',
        'Har du någonsin haft några penslar med berömmelse eller kändis?',
        'Kan du göra något trick? T.ex. på skateboard eller liknande.',
        'Sover du någonsin mitt på dagen och ändå kan sova på natten?',
        'Har du ärr?',
        'Vad är det skämmigaste du gjort på fyllan?',
        'Hur många mattor äger du?',
        'Kommer du ihåg gamla barnprogram som typ Dr. Snuggles, Björnes magasin, Ducktales eller liknande?',
        'Föredrar du ljudbok över en vanlig bok?',
        'Duschar du länge eller snabbt?',
        'Hur länge sitter du vid datorn hemma?',
        'Hur mycket pengar lägger du på spel varje månad?',
        'Har du några åsikter om aktuella samhällsfrågor?',
        'Har du hellre korta strumpor eller fullstora?',
        'Är det konstigt att en person saknar gardiner?',
        'Hur vet man att en ungkarl bor ensam?',
        'Är kall dusch bättre än varm?',
        'Har du någonsin snickrat eller renoverat något?',
        'Har du lätt för att ta hand om plantor?',
        'Berätta något jag inte vet om dig.',
        'Släcker du lamporna om du inte är i rummet?',
        'Skulle du välja att bo i hus även trots att du måste skotta och kratta själv?',
        'Tycker du att tid går fort eller långsamt?',
        'Glömmer du lätt att du har något planerat?',
        'Berätta något som alla antar om dig.',
        'Har du en favoritdoft?',
        'Brukar du ha munskydd när du besöker allmänna platser?',
        'Tuggar du på naglarna?',
        'Underställ när det är kallt?',
        'Har du någonsin ätit macka utan pålägg?',
        'Tvättar du undersidan av dina fötter när du duschar?',
        'Poppar du alla luftbubblorna på bubbelplast?',
        'Är det fel att inte ha tavlor?',
        'Kom du ihåg att göra det du skulle?',
        'Playstation eller Nintendo?',
        'Vad är det manligaste och kvinnligaste du vet?',
        'Visste du att bananer är radioaktiva?',
        'Violets are blue, You look like a donkey, And smell like one, too.',
        'Rensar du någonsin duschen från hår?',
        'Hur länge sitter du med telefonen dagligen?',
        'Är att ge saker till människor ett sätt att visa kärlek?',
        'Blickar du tillbaka på vad som varit och tänker på vad du inte hunnit eller aldrig tog initiativ att göra?',
    ];
    increment = () => {
        this.counter++;
        if (this.counter > this.length) this.counter = 1;
        this.updateDisplay();
    }
    decrement = () => {
        this.counter--;
        if (this.counter < 1) this.counter = this.length;
        this.updateDisplay();
    }
    randomize = () => {
        this.counter = Math.floor(
            Math.random() * this.length
        ) + 1;
        this.updateDisplay();
    }
    checkSentenceExists = (p0) => {
        return new Promise((resolve, reject) => {
            if(document.location.origin === "http://127.0.0.1:5500"){
                setTimeout(() => {
                    for (let i = 0; i < this.length; i++) {
                        const sentenceWords = new Set(this.topics[i].split(" "));
                        sentenceWords.forEach((word) => {
                            const count = this.frequencyMap.get(word) || new Array(this.length).fill(0);
                            count[i]++;
                            this.frequencyMap.set(word, count);
                        });
                    }
                    
                    const p0Words = p0.split(" ");
                    for (let i = 0; i < p0Words.length; i++) {
                        const counts = this.frequencyMap.get(p0Words[i]);
                        if (!counts) {
                            reject(p0Words[i]);
                        }
                    
                        for (let j = 0; j < this.length; j++) {
                            if (counts[j] !== (p0Words.filter((word) => word === p0Words[i]).length * (this.topics[j].split(" ").filter((word) => word === p0Words[i]).length))) {
                                break;
                            }
                            if (j === this.length - 1) {
                                resolve(true);
                            }
                        }
                    }
                });
            } else{
                reject(false);
            }
        });
    }
    updateLink() {
        const element = document.getElementById('link');
        const newData = this.topics[this.counter - 1];
        const currentIndex = this.length == 0 ? 1 : this.counter;
        document.getElementById('container').innerHTML = newData;
        document.querySelector('meta[name="description"]').setAttribute("content", newData);
        element.innerHTML = `${currentIndex} / ${this.length}`;
        element.href = document.location.origin + `?topic=${currentIndex}`;
        element.href += this.nsfw ? '&nsfw' : '';
        element.href += this.searching ? '&question=' + this.searchWord : '';
    }
    overrideQuestionText(text) {
        document.getElementById('container').innerHTML = text;
    }
    toggleText() {
        if (this.length >= 1) {
            document.getElementById('container').classList.remove('hidetext');
            document.getElementById('link').classList.remove('hidetext');
        } else {
            //document.getElementById('container').classList.add('hidetext');
            document.getElementById('link').classList.add('hidetext');
        }
    }
    updateDisplay() {
        this.updateLink();
        this.toggleText();

        if (this.length < 1) {
            this.counter = 0;
            this.overrideQuestionText("Din sökning gav inget resultat.");
        }
    }
    jumpToTopic(num){
        this.counter = num;
        questions.updateDisplay();
    }
    parseParam = (e) => {
        var t = void 0;
        return (
            window.location.search.split('&').forEach(function (n) {
                (n = n.replace('?', '')).split('=')[0] == e &&
                    (t = decodeURIComponent(n.split('=')[1]));
            }),
            t
        );
    }
    sendNotification = (text) => {
        const notification = document.createElement('div');
        this.aliveNotifications++;
        notification.id = 'notification-' + this.aliveNotifications;
        notification.innerText = text;
        notification.style.left = '50%';
        notification.style.position = 'absolute';
        notification.style.top = this.aliveNotifications * 45 + 'px';
        notification.classList.add('notification');
        document.body.appendChild(notification);
        const liveNotification = document.getElementById(
            'notification-' + this.aliveNotifications
        );
        liveNotification.style.transform = `translateX(-${liveNotification.getBoundingClientRect().width / 2
            }px)`;
        setTimeout(() => {
            notification.classList.add('fadeOut');
        }, 900);
        setTimeout(() => {
            document.body.removeChild(notification);
            this.aliveNotifications--;
        }, 2100);
    }
    invalidateSearch = () => {
        this.searchWord = "";
        this.searching = false;
        this.updateDisplay();
    }
    doFilterSearch = (parm) => {
        const target = document.getElementById("filter");
        target.style.width = target.value.length + 'ch';
        this.searchWord = parm;
        this.searching = this.searchWord.length > 0;
        try {
            this.topics = !this.nsfw ? this.shadowTopics.filter((x) =>
                new RegExp(parm, 'gmdi').test(x)
            ) : this.shadowTopics.concat(this.sensitive_topics).filter((x) =>
                new RegExp(parm, 'gmdi').test(x)
            );
            if (this.topics.length > 0) {
                this.counter = 1;
            }
        } catch {
            //do nothing luls :)
        }
        this.updateDisplay();
    }
    addEventListeners = () => {
        const inputText = document.getElementById('filter');
        inputText.addEventListener('input', (event) => {
            questions.doFilterSearch(event.target.value);
        });

        document.addEventListener('keydown', function (event) {
            if (event.ctrlKey && event.code === 'KeyC') {
                copy();
            }
        });
    }
    initializeComponent = () => {
        const inputText = document.getElementById('filter');
        const parm = questions.parseParam('question');
        if (parm != null) {
            inputText.value = parm != null ? parm : '';
            questions.doFilterSearch(parm);
        }
        const arr = document.lastModified.substring(0,8).split("/").reverse().join("-") + " " + document.lastModified.substring(11);
        document.getElementById("modified").innerHTML = arr;
        if (this.parseParam("nsfw")) {
            this.nsfw = true;
            document.getElementById('unsafe').checked = true;
            unsafe_check({ checked: true });
        }
        if (this.parseParam("topic") === undefined) {
            this.randomize();
        } else {
            let value = this.parseParam("topic");
            if (value.length > 0) {
                this.counter = Number(this.parseParam("topic"));
                this.updateDisplay();
            }
            else {
                if (!this.searching) {
                    this.randomize();
                }
            }
        }

        this.findDuplicates();
        this.addEventListeners();
    }
}